"""systemd drop-ins for each registered job, over the session-ops@ templates.

The templates in deploy/ carry what every job shares, hardening included; a job's
drop-in carries only what jobs.toml says about it. Generated, so the registry is the
one place a schedule, an account or a secret file is set.
"""
import os

HEADER = "# Generated by `session-ops units` from jobs.toml. Edit the registry, not this.\n"


def service_dropin(job):
    lines = [HEADER, "[Unit]", f"Description={job.description}", "", "[Service]",
             f"User={job.user}", f"Group={job.user}"]
    lines += [f"EnvironmentFile={path}" for path in job.env_files]
    lines.append(f"TimeoutStartSec={job.timeout}")
    lines += list(job.unit)
    return "\n".join(lines) + "\n"


def timer_dropin(job):
    return "\n".join([HEADER, "[Timer]", f"OnCalendar={job.schedule}"]) + "\n"


def dropins(jobs):
    """{relative path: content} for every job."""
    files = {}
    for job in jobs:
        files[f"session-ops@{job.name}.service.d/job.conf"] = service_dropin(job)
        if job.schedule:
            files[f"session-ops@{job.name}.timer.d/schedule.conf"] = timer_dropin(job)
    return files


def write(jobs, out):
    written = []
    for relative, content in sorted(dropins(jobs).items()):
        path = os.path.join(out, relative)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        written.append(path)
    return written
