"""systemd drop-ins for each registered job, over the session-ops@ templates.

The templates in deploy/ carry what every job shares, hardening included; a job's
drop-in carries only what jobs.toml says about it. Generated, so the registry is the
one place a schedule, an account or a secret file is set.
"""
import json
import os

HEADER = "# Generated by `session-ops units` from jobs.toml. Edit the registry, not this.\n"
# The account session-ops-discord.service runs as, and install.sh creates.
RELAY_USER = "opsbot"


def service_dropin(job):
    lines = [HEADER, "[Unit]", f"Description={job.description}"]
    if job.after:
        # Orders this after whichever of them are started too; never pulls one in.
        lines.append("After=" + " ".join(f"session-ops@{name}.service" for name in job.after))
    lines += ["", "[Service]", f"User={job.user}", f"Group={job.user}"]
    lines += [f"EnvironmentFile={path}" for path in job.env_files]
    lines.append(f"TimeoutStartSec={job.timeout}")
    lines += list(job.unit)
    return "\n".join(lines) + "\n"


def timer_dropin(schedule):
    return "\n".join([HEADER, "[Timer]", f"OnCalendar={schedule}"]) + "\n"


def path_dropin(pattern):
    return "\n".join([HEADER, "[Path]", f"PathExistsGlob={pattern}"]) + "\n"


def dropins(jobs, queue):
    """{relative path: content} for every job, and the queue's schedule.

    Which queued jobs the queue starts is install.sh's to decide, from their env files:
    it links each ready one into session-ops-queue.service.wants/.
    """
    files = {}
    if queue.schedule:
        files["session-ops-queue.timer.d/schedule.conf"] = timer_dropin(queue.schedule)
    for job in jobs:
        files[f"session-ops@{job.name}.service.d/job.conf"] = service_dropin(job)
        if job.schedule:
            files[f"session-ops@{job.name}.timer.d/schedule.conf"] = timer_dropin(job.schedule)
        if job.watch:
            files[f"session-ops@{job.name}.path.d/watch.conf"] = path_dropin(job.watch_glob)
    return files


def polkit_rule(jobs):
    """Lets the Discord relay's account start the jobs offered to `/run`, and nothing else."""
    allowed = json.dumps([f"session-ops@{job.name}.service" for job in jobs if job.discord])
    return f"""// Generated by `session-ops polkit` from jobs.toml. Edit the registry, not this.
polkit.addRule(function(action, subject) {{
    if (action.id == "org.freedesktop.systemd1.manage-units" &&
        subject.user == "{RELAY_USER}" &&
        action.lookup("verb") == "start" &&
        {allowed}.indexOf(action.lookup("unit")) >= 0) {{
        return polkit.Result.YES;
    }}
}});
"""


def write(jobs, queue, out):
    written = []
    for relative, content in sorted(dropins(jobs, queue).items()):
        path = os.path.join(out, relative)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        written.append(path)
    return written
