name: 'Setup for all'
description: "Setup shared for all jobs"
inputs:
  token:
    description: 'Token to use for checkout (required for push access)'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
      - name: Checkout Localization Module
        uses: actions/checkout@v4
        with:
          repository: 'session-foundation/session-localization'
          path: 'module'
          ref: 'main'
          token: ${{ inputs.token }}

      - name: Remove existing strings
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/generated/*
