name: 'Setup for all'
description: "Setup shared for all jobs"
runs:
  using: 'composite'
  steps:
      - name: Checkout Desktop
        uses: actions/checkout@v4
        with:
          repository: 'session-foundation/session-desktop'
          path: 'desktop'
          ref: 'dev'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'desktop/.nvmrc'

      - name: Remove existing strings
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/desktop/_locales/*