on:
    pull_request:
      # Sequence of patterns matched against refs/heads
      branches:
        - main
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        shell: bash
        run: |
          pip install -r ${{ github.workspace }}/scripts/crowdin/requirements.txt

      - name: Lint python (use black `crowdin` before push)
        shell: bash
        run: |
          black crowdin --check